### ISSUE TITLE
Videos from database

### ISSUE THREAD

**Issue by RaviKumarK25** [codeByVaibhav/tiktok_clone#1]
Hi Vaibhav,

Can you share the details that how to get videos from database like from firebase or other database. I am learning Flutter so this will be very useful if you guide me how to get videos from firebase and play like as static this app.

**Comment by codeByVaibhav** [comment]
@RaviKumarK25 I have not tried connecting to any database yet. I think I will try firebase or aws.

**Comment by RaviKumarK25** [comment]
@codeByVaibhav I am learning Flutter so your code is helping me so please try with database i want to know how it is work. Thanks for sharing your knowledge.

**Comment by codeByVaibhav** [comment]
I am glad I am helpful to you. I am working on the user database and video streaming using firebase.

**Comment by RaviKumarK25** [comment]
I am waiting for your next updated app code.

**Comment by codeByVaibhav** [comment]
It will take time because I am working on some other project.

**Comment by RaviKumarK25** [comment]
Okay, i will wait. Thanks for your reply.
